// Tenants for the Data Table stories — the rows from apps/chat's
// DataTablePage, lifted out so a story can import them. Packages never import
// from an app.
export type TenantStatus = 'active' | 'pending' | 'suspended'

export type Tenant = {
  id: string
  name: string
  initials: string
  status: TenantStatus
  contact: string
  email: string
  phone: string
  created: string
  tier: 'Enterprise' | 'Growth' | 'Starter'
  seats: [number, number]
  region: string
  renewal: string
}

export const TENANTS: Tenant[] = [
  {
    id: 'tnt_8f42c19b',
    name: 'Crestview Bank',
    initials: 'CB',
    status: 'active',
    contact: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    phone: '908 645 3454',
    created: '2026-03-14',
    tier: 'Enterprise',
    seats: [412, 500],
    region: 'Northeast · NJ',
    renewal: '2026-09-30',
  },
  {
    id: 'tnt_2a77de05',
    name: 'Prosperity Bank',
    initials: 'PB',
    status: 'active',
    contact: 'Michael Smith',
    email: 'michael.s@example.com',
    phone: '654 765 2344',
    created: '2026-03-12',
    tier: 'Growth',
    seats: [88, 120],
    region: 'Midwest · IL',
    renewal: '2026-11-01',
  },
  {
    id: 'tnt_51c0b3aa',
    name: 'Liberty Savings & Loan',
    initials: 'LS',
    status: 'pending',
    contact: 'Emily Brown',
    email: 'emily.b@example.com',
    phone: '908 645 3454',
    created: '2026-03-09',
    tier: 'Starter',
    seats: [12, 25],
    region: 'Northeast · NY',
    renewal: '2027-01-15',
  },
  {
    id: 'tnt_9d31f7c2',
    name: 'Horizon National Bank',
    initials: 'HB',
    status: 'active',
    contact: 'David Rodriguez',
    email: 'david.r@example.com',
    phone: '856 746 8576',
    created: '2026-02-28',
    tier: 'Enterprise',
    seats: [903, 1000],
    region: 'West · CA',
    renewal: '2026-08-12',
  },
  {
    id: 'tnt_6b18ae44',
    name: 'Capital Trust Bank',
    initials: 'CT',
    status: 'suspended',
    contact: 'Jessica Nguyen',
    email: 'jessica.n@example.com',
    phone: '908 645 3454',
    created: '2026-02-21',
    tier: 'Growth',
    seats: [0, 150],
    region: 'South · TX',
    renewal: '2026-06-30',
  },
  {
    id: 'tnt_c402e8d1',
    name: 'Integrity Financial Corp.',
    initials: 'IC',
    status: 'active',
    contact: 'Christopher Lee',
    email: 'christopher.l@example.com',
    phone: '856 746 8576',
    created: '2026-02-14',
    tier: 'Enterprise',
    seats: [287, 400],
    region: 'Northeast · MA',
    renewal: '2026-12-01',
  },
  {
    id: 'tnt_7e95ba30',
    name: 'Summit Community Bank',
    initials: 'SB',
    status: 'active',
    contact: 'Ashley Taylor',
    email: 'ashley.t@example.com',
    phone: '908 645 3454',
    created: '2026-02-02',
    tier: 'Starter',
    seats: [19, 25],
    region: 'Midwest · OH',
    renewal: '2027-02-02',
  },
  {
    id: 'tnt_1f6cd982',
    name: 'Pinnacle Credit Union',
    initials: 'PC',
    status: 'pending',
    contact: 'Daniel Okafor',
    email: 'daniel.o@example.com',
    phone: '415 220 7781',
    created: '2026-01-27',
    tier: 'Growth',
    seats: [44, 120],
    region: 'West · WA',
    renewal: '2026-10-19',
  },
  {
    id: 'tnt_ab3390ef',
    name: 'Granite State Savings',
    initials: 'GS',
    status: 'active',
    contact: 'Priya Raman',
    email: 'priya.r@example.com',
    phone: '603 118 2290',
    created: '2026-01-19',
    tier: 'Enterprise',
    seats: [512, 600],
    region: 'Northeast · NH',
    renewal: '2026-07-22',
  },
  {
    id: 'tnt_44de1207',
    name: 'Bayshore Financial',
    initials: 'BF',
    status: 'active',
    contact: 'Marcus Webb',
    email: 'marcus.w@example.com',
    phone: '305 774 9912',
    created: '2026-01-11',
    tier: 'Growth',
    seats: [61, 120],
    region: 'South · FL',
    renewal: '2026-09-05',
  },
  {
    id: 'tnt_08bb5e73',
    name: 'Ironwood Mutual',
    initials: 'IM',
    status: 'suspended',
    contact: 'Helen Park',
    email: 'helen.p@example.com',
    phone: '312 665 4401',
    created: '2025-12-30',
    tier: 'Starter',
    seats: [0, 25],
    region: 'Midwest · MI',
    renewal: '2026-05-30',
  },
  {
    id: 'tnt_ee7712c8',
    name: 'Northgate Trust',
    initials: 'NT',
    status: 'active',
    contact: 'Tomas Alvarez',
    email: 'tomas.a@example.com',
    phone: '206 889 3345',
    created: '2025-12-18',
    tier: 'Enterprise',
    seats: [744, 800],
    region: 'West · OR',
    renewal: '2026-11-18',
  },
  {
    id: 'tnt_3c9a0b61',
    name: 'Fairfield Savings',
    initials: 'FS',
    status: 'pending',
    contact: 'Nia Coleman',
    email: 'nia.c@example.com',
    phone: '203 442 7756',
    created: '2025-12-04',
    tier: 'Growth',
    seats: [30, 120],
    region: 'Northeast · CT',
    renewal: '2026-12-04',
  },
  {
    id: 'tnt_5da6f4e9',
    name: 'Redstone Bancorp',
    initials: 'RB',
    status: 'active',
    contact: 'Owen Fitzgerald',
    email: 'owen.f@example.com',
    phone: '720 331 8890',
    created: '2025-11-22',
    tier: 'Growth',
    seats: [97, 120],
    region: 'West · CO',
    renewal: '2026-08-30',
  },
]

export const STATUS_TONE = { active: 'brand', pending: 'warning', suspended: 'danger' } as const
export const STATUS_LABEL = {
  active: 'Active',
  pending: 'Pending',
  suspended: 'Suspended',
} as const

export const fmtDate = (iso: string) =>
  new Date(`${iso}T00:00:00`).toLocaleDateString('en-US', {
    month: 'short',
    day: '2-digit',
    year: 'numeric',
  })
